#!/usr/bin/env node
// Generates the TypeScript client from openapi.json.
//
// Doctrine §7: Rust is the single source of truth. This script never invents a
// type — it only transcribes what utoipa emitted. `just drift` regenerates and
// fails CI if the checked-in output no longer matches, which is what makes the
// contract a gate rather than a convention.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const spec = JSON.parse(readFileSync(resolve(root, "openapi.json"), "utf8"));

const RESERVED = new Set(["default"]);
const safeName = (n) => (RESERVED.has(n) ? `${n}_` : n.replace(/[^A-Za-z0-9_]/g, "_"));

function tsType(schema, depth = 0) {
  if (!schema) return "unknown";
  if (schema.$ref) return safeName(schema.$ref.split("/").pop());
  if (schema.allOf?.length === 1) return tsType(schema.allOf[0], depth);
  if (schema.oneOf) return schema.oneOf.map((s) => tsType(s, depth + 1)).join(" | ");
  if (schema.anyOf) return schema.anyOf.map((s) => tsType(s, depth + 1)).join(" | ");
  if (schema.enum) return schema.enum.map((v) => JSON.stringify(v)).join(" | ");

  switch (schema.type) {
    case "string": return "string";
    case "boolean": return "boolean";
    case "integer":
    case "number": return "number";
    case "array": return `${tsType(schema.items, depth + 1)}[]`;
    case "object": {
      const props = schema.properties ?? {};
      const required = new Set(schema.required ?? []);
      const entries = Object.entries(props);
      if (entries.length === 0) {
        return schema.additionalProperties
          ? `Record<string, ${tsType(schema.additionalProperties, depth + 1)}>`
          : "Record<string, unknown>";
      }
      const pad = "  ".repeat(depth + 1);
      const body = entries
        .map(([k, v]) => `${pad}${JSON.stringify(k)}${required.has(k) ? "" : "?"}: ${tsType(v, depth + 1)};`)
        .join("\n");
      return `{\n${body}\n${"  ".repeat(depth)}}`;
    }
    default:
      if (schema.properties) return tsType({ ...schema, type: "object" }, depth);
      return "unknown";
  }
}

const out = [];
out.push("// GENERATED BY `just client` FROM openapi.json — DO NOT EDIT.");
out.push("// Doctrine §7: Rust is the single source of truth. Edit the Rust, then");
out.push("// run `just openapi client`. CI fails on drift.");
out.push("");

const schemas = spec.components?.schemas ?? {};
for (const [name, schema] of Object.entries(schemas).sort(([a], [b]) => a.localeCompare(b))) {
  const doc = schema.description ? `/** ${schema.description.split("\n")[0]} */\n` : "";
  out.push(`${doc}export type ${safeName(name)} = ${tsType(schema)};`);
  out.push("");
}

out.push("export interface VeltClientOptions {");
out.push("  /** Loopback base URL, e.g. http://127.0.0.1:47821 */");
out.push("  baseUrl: string;");
out.push("  fetch?: typeof globalThis.fetch;");
out.push("}");
out.push("");
out.push("export class VeltApiError extends Error {");
out.push("  constructor(readonly status: number, readonly body: unknown) {");
out.push("    super(`VELT daemon returned ${status}`);");
out.push("    this.name = \"VeltApiError\";");
out.push("  }");
out.push("}");
out.push("");
out.push("export function createClient(options: VeltClientOptions) {");
out.push("  const doFetch = options.fetch ?? globalThis.fetch;");
out.push("  const base = options.baseUrl.replace(/\\/$/, \"\");");
out.push("");
out.push("  async function request<T>(path: string, init?: RequestInit): Promise<T> {");
out.push("    const res = await doFetch(`${base}${path}`, {");
out.push("      ...init,");
out.push("      headers: { \"content-type\": \"application/json\", ...(init?.headers ?? {}) },");
out.push("    });");
out.push("    const body = res.status === 204 ? null : await res.json();");
out.push("    if (!res.ok) throw new VeltApiError(res.status, body);");
out.push("    return body as T;");
out.push("  }");
out.push("");

for (const [path, ops] of Object.entries(spec.paths ?? {})) {
  for (const [method, op] of Object.entries(ops)) {
    const name = op.operationId ?? `${method}${path.replace(/\W+/g, "_")}`;
    const ok = op.responses?.["200"]?.content?.["application/json"]?.schema;
    const ret = ok ? tsType(ok) : "void";
    const reqSchema = op.requestBody?.content?.["application/json"]?.schema;
    const summary = (op.summary ?? op.description ?? "").split("\n")[0];
    if (summary) out.push(`  /** ${summary} */`);
    if (reqSchema) {
      out.push(`  async function ${name}(body: ${tsType(reqSchema)}): Promise<${ret}> {`);
      out.push(`    return request<${ret}>(${JSON.stringify(path)}, { method: ${JSON.stringify(method.toUpperCase())}, body: JSON.stringify(body) });`);
    } else {
      out.push(`  async function ${name}(): Promise<${ret}> {`);
      out.push(`    return request<${ret}>(${JSON.stringify(path)}, { method: ${JSON.stringify(method.toUpperCase())} });`);
    }
    out.push("  }");
    out.push("");
  }
}

const names = Object.entries(spec.paths ?? {})
  .flatMap(([path, ops]) =>
    Object.entries(ops).map(([m, op]) => op.operationId ?? `${m}${path.replace(/\W+/g, "_")}`)
  );
out.push(`  return { ${names.join(", ")} };`);
out.push("}");
out.push("");
out.push("export type VeltClient = ReturnType<typeof createClient>;");
out.push("");

writeFileSync(resolve(root, "packages/api-client/src/generated.ts"), out.join("\n"));
console.log(`generated packages/api-client/src/generated.ts (${Object.keys(schemas).length} schemas, ${names.length} operations)`);
