// GENERATED BY `just client` FROM openapi.json — DO NOT EDIT.
// Doctrine §7: Rust is the single source of truth. Edit the Rust, then
// run `just openapi client`. CI fails on drift.

/** Error body returned for a rejected underwrite. */
export type ApiError = {
  "code": string;
  "detail": string;
};

/** A rate in basis points scaled by [`Bps::SCALE`] (1 bp = 1/100 of a percent). */
export type Bps = number;

/** ISO-4217 currencies VELT supports. */
export type Currency = "USD" | "EUR" | "GBP" | "CAD" | "MXN";

/** Acquisition and financing terms. */
export type DealInputs = {
  "closing_costs": Money;
  "down_payment_rate": Bps;
  "interest_rate": Bps;
  "purchase_price": Money;
  "rehab_budget": Money;
  "term_months": number;
};

/** The operating expense assumptions for a property. */
export type ExpenseInputs = {
  "annual_hoa": Money;
  "annual_insurance": Money;
  "annual_other_fixed": Money;
  "annual_property_tax": Money;
  "annual_utilities": Money;
  "capex_reserve_rate": Bps;
  "maintenance_rate": Bps;
  "management_rate": Bps;
};

/** Liveness and version response. */
export type Health = {
  "engine_version": string;
  "status": string;
};

/** The rent roll and income assumptions for a property. */
export type IncomeInputs = {
  "monthly_scheduled_rent": Money;
  "other_annual_income": Money;
  "vacancy_rate": Bps;
};

/** A monetary amount, stored as signed integer minor units. */
export type Money = {
  "currency": Currency;
  "minor": number;
};

/** A value carrying the trace that produced it. */
export type Traced_Bps = {
  "trace": Trace;
  "value": number;
};

/** A value carrying the trace that produced it. */
export type Traced_Money = {
  "trace": Trace;
  "value": {
    "currency": Currency;
    "minor": number;
  };
};

/** A completed underwrite. Every field carries its derivation. */
export type Underwrite = {
  "annual_debt_service": Traced_Money;
  "break_even_occupancy": Traced_Bps;
  "cap_rate": Traced_Bps;
  "cash_flow_before_tax": Traced_Money;
  "cash_on_cash": Traced_Bps;
  "dscr": Traced_Bps;
  "effective_gross_income": Traced_Money;
  "expense_ratio": Traced_Bps;
  "gross_potential_rent": Traced_Money;
  "gross_rent_multiplier": Traced_Bps;
  "loan_amount": Traced_Money;
  "net_operating_income": Traced_Money;
  "operating_expenses": Traced_Money;
  "total_cash_invested": Traced_Money;
  "vacancy_loss": Traced_Money;
};

/** The full input set for an underwrite. */
export type UnderwriteInputs = {
  "deal": DealInputs;
  "expenses": ExpenseInputs;
  "income": IncomeInputs;
};

/** Request body for an underwrite. */
export type UnderwriteRequest = {
  "inputs": UnderwriteInputs;
};

export interface VeltClientOptions {
  /** Loopback base URL, e.g. http://127.0.0.1:47821 */
  baseUrl: string;
  fetch?: typeof globalThis.fetch;
}

export class VeltApiError extends Error {
  constructor(readonly status: number, readonly body: unknown) {
    super(`VELT daemon returned ${status}`);
    this.name = "VeltApiError";
  }
}

export function createClient(options: VeltClientOptions) {
  const doFetch = options.fetch ?? globalThis.fetch;
  const base = options.baseUrl.replace(/\/$/, "");

  async function request<T>(path: string, init?: RequestInit): Promise<T> {
    const res = await doFetch(`${base}${path}`, {
      ...init,
      headers: { "content-type": "application/json", ...(init?.headers ?? {}) },
    });
    const body = res.status === 204 ? null : await res.json();
    if (!res.ok) throw new VeltApiError(res.status, body);
    return body as T;
  }

  /** Liveness probe. */
  async function health(): Promise<Health> {
    return request<Health>("/health", { method: "GET" });
  }

  /** Run an underwrite. */
  async function post_underwrite(body: UnderwriteRequest): Promise<Underwrite> {
    return request<Underwrite>("/underwrite", { method: "POST", body: JSON.stringify(body) });
  }

  return { health, post_underwrite };
}

export type VeltClient = ReturnType<typeof createClient>;
